[build]
command = "curl -fsSL https://quarto.org/download/latest/quarto-linux-amd64.deb -o quarto.deb && dpkg -x quarto.deb .quarto && export PATH=$PATH:$(pwd)/.quarto/usr/bin && quarto render matshie_website"
publish = "matshie_website/_site"