[build]
command = "curl -fsSL https://quarto.org/download/latest/install-linux.sh | bash -s -- -p $PWD/.quarto && export PATH=$PWD/.quarto/bin:$PATH && quarto render matshie_website"
publish = "matshie_website/_site"

